
name: Snake Grid Animation CI

on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
  
  push:
    branches:
    - main

jobs:
  generate-snake-grid-animation:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: generate snake-grid-animation svgs
        uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-grid-animation.svg
            dist/github-snake-grid-dark-animation.svg?palette=github-dark
            dist/github-snake-grid-custom-animation.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      - name: push snake-grid-animation svgs
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: snake-grid-animations
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
